



---
apiVersion:v1
kind: Pod
metdata: 
  name: frontendpod
  labels: 
      tier: frontend 
spec: 
   containers:
      name: php-redis
      image: nginx



---
apiVersion: v1
kind: Service
metadata:
     name: webapp-service 
spec:
  type : NodePort
  ports:
     - targetPort: 80
       port: 80
       nodePort: 300005
       protocol: TCP
  selector: 
      app: vproapp

---

apiVersion: apps/v1      (below is same to same but it is accurate below one having some mistakes )
kind: Replicaset
metadata:
    name: frontend
    labels: 
      app: guestbook
      tier: frontend
spec:
    replicas: 3
    selector:
       matchlabels: 
            tier: frontend
    template:
       metadata:
          labels: 
             tier: frontend 
       spec:
          containers:       
            - name: php-redis 
              image: nginx

apiVersion: apps/v1
kind: ReplicaSet 
metadata:
     labels:
        tier: frontend 
     name: frontendpod
spec:
   replicas: 3
   selector:
       matchlabels:
          tier: frontend 
   template:
      metadata:
         labels:
            tier: frontend
      spec:      
         containers:
            - name: frontendcontainer
              images: nginx



// yha se app deployment on kubernetes cluster by imran teli devops course 

// secret file for the database 

apiVersion: v1
kind: Secret 
metadata:
   name: app-secret 
type: Opaque 
data:
   db-pass: encodedforrm of password
   rmq-pass: encodedformofpassword



// deployment file for database 


apiVersion: apps/v1
kind: Deployment 
metadata:
    name: vprodb
    labels:
       app: vprodb

spec:
   selector:
      matchLabels:
           app: vprodb
   replicas: 1
   template:
       metadata:
         labels: 
              app: vprodb

       spec:
         containers:
            -  name: vprodb
               image: vprofile/vprofiledb:v1
               args:
                  - "--ignore-db-dir=lost+found"
               volumeMounts:
                  - mountPath: /var/lib/mysql
                    name: vpro-db-data
               ports:
                  - name: vprodb-port
                    containerPort: 3306
               env:
                  - name: MYSQLROOT_PASSWORD
                    valueFrom:
                       secretKeyRef:
                          name: app-secret
                          key: db-pass
         nodeSelector:
             zone: us-east-2a
         volumes:
            - name : vpr-db-data
              awsElasticBlockStore:
                 volumeID: vol-00009034
                 fsType: ext4




// service file for the database 

apiVersion: v1
kind: Service
metadata:
    name:  vprodb
spec:
   ports:
     - port: 3306
       targetPort: vprodb-port
       protocol: TCP
   selector:
        app:  vprodb
   type: ClusterIP  

// end  



